plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.example.appxx_appthemewallpaper'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.appxx_appthemewallpaper"
        minSdk 26
        targetSdk 36
        versionCode 100
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        def formattedDate = new Date().format('MM.dd.yyyy')
        archivesBaseName = "Appxx_AppTheme_Wallpaper_v${versionName}_${formattedDate}"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions("default")
    productFlavors {
        develop {

        }

        production {

        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
    }

    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }

    lintOptions {
        abortOnError false
        checkAllWarnings false
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation 'com.intuit.ssp:ssp-android:1.1.1'
    implementation 'com.intuit.sdp:sdp-android:1.1.1'
    implementation("com.airbnb.android:lottie:6.5.2")
    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.code.gson:gson:2.13.1'

    implementation("com.github.minh-nguyen-2003:view_mover:1.0.0")

}